language: node_js
node_js:
- stable
cache:
  directory:
  - node_modules
addons:
  apt:
    update: true
    packages:
    - node-semver
    - wine
before_install: true
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm run test
after_success:
- git config --local user.name "Nonce CI-CD Worker"
- git config --local user.name "dev@nonce.community"
- CURRENT_VERSION=$(node -p "require('./package.json').version")
- if [ "$TRAVIS_BRANCH" = "master" ]; then echo "on master branch"; export TRAVIS_TAG=v$CURRENT_VERSION-release;
  fi;
- if [ "$TRAVIS_BRANCH" = "develop" ]; then echo "on develop branch"; PREV_RC=$(git
  tag -l "v$CURRENT_VERSION-rc*" | tail -1); if [ $PREV_RC ]; then export TRAVIS_TAG=v$(semver
  $PREV_RC -i prerelease --preid rc); else export TRAVIS_TAG=v$(semver $CURRENT_VERSION-rc.1);
  fi; fi;
- echo "Version $TRAVIS_TAG is tagged"
before_deploy:
- npm run package-mac
- npm run package-linux
- npm run package-win
- tar czf builds/nonce-tools-app-darwin-x64.tar.gz builds/nonce-tools-app-darwin-x64
- tar czf builds/nonce-tools-app-linux-x64.tar.gz builds/nonce-tools-app-linux-x64
- tar czf builds/nonce-tools-app-win32-ia32.tar.gz builds/nonce-tools-app-win32-ia32

deploy:
  - provider: releases
    api_key:
      secure: WN1Wc16t/ZvPSw54PIEV1VJ75w0WcqGjnpADLjXHJT0hraRn9O6wswxOD/EbFt4OY0G/8TQimQlwRxghPv69UvshZHDS2/A5rfM7153ejtr7reMEnH46qcBNIFloUB4/Nemu1cphMDis06Av88DR5nUhyQvuWYDZc4lXHtwy99eR8Pnvb9KBxgZn9OajPddnCqMDlkzYVTbqyzER3bM9Qkgzp+mBPcOkN65rAGlcOk7Pt6FY4JZIhVO5Byhg0ZTn28bo6e1taxohx3gaD/FbHt6I++ZWGknetJpsgx5UMdh00l/P1/sZvQ1R/RiigEz7GbmmGNLjaIWLp1WTiP7ooAq8UuQi6/cYUoNeoUVEHmzbnsC51vnKG60Dsj0tX/iLmKvkU6VF/Zuv1HbxfO4qLKFvvTnEGZjFzTlPjQIlWD9siOfZY5lqE0FyYf4w9wNzXOXBesTxOb5qUEXRYUWb9k2Xnu2Nf8x4Id6+u7QbfhpuRBuU4SSvlcElSU0UFTDL1Fij4MwenAXNevh4+p3VQePTNY1Mil72l5HBfsDPg2byK2xuPYsiN5gx3AmHKsDk/SdZB5E2X5WO25RNeW3uNGjCEmfar+gYa5JryauWk0xb3FnN9wnmTrSgd58t6d0KM8dhJ95Et/T7nlnXcZvtlm5K216rtvRNBmqV3BTK1OY=
    file:
      - builds/nonce-tools-app-darwin-x64.tar.gz
      - builds/nonce-tools-app-linux-x64.tar.gz
      - builds/nonce-tools-app-win32-ia32.tar.gz
    skip_cleanup: true
    overwrite: true
    prerelease: false
    on:
      branch: master
      repo: nonce-community/nonce-work-tools
      tags: true
  - provider: releases
    api_key:
      secure: WN1Wc16t/ZvPSw54PIEV1VJ75w0WcqGjnpADLjXHJT0hraRn9O6wswxOD/EbFt4OY0G/8TQimQlwRxghPv69UvshZHDS2/A5rfM7153ejtr7reMEnH46qcBNIFloUB4/Nemu1cphMDis06Av88DR5nUhyQvuWYDZc4lXHtwy99eR8Pnvb9KBxgZn9OajPddnCqMDlkzYVTbqyzER3bM9Qkgzp+mBPcOkN65rAGlcOk7Pt6FY4JZIhVO5Byhg0ZTn28bo6e1taxohx3gaD/FbHt6I++ZWGknetJpsgx5UMdh00l/P1/sZvQ1R/RiigEz7GbmmGNLjaIWLp1WTiP7ooAq8UuQi6/cYUoNeoUVEHmzbnsC51vnKG60Dsj0tX/iLmKvkU6VF/Zuv1HbxfO4qLKFvvTnEGZjFzTlPjQIlWD9siOfZY5lqE0FyYf4w9wNzXOXBesTxOb5qUEXRYUWb9k2Xnu2Nf8x4Id6+u7QbfhpuRBuU4SSvlcElSU0UFTDL1Fij4MwenAXNevh4+p3VQePTNY1Mil72l5HBfsDPg2byK2xuPYsiN5gx3AmHKsDk/SdZB5E2X5WO25RNeW3uNGjCEmfar+gYa5JryauWk0xb3FnN9wnmTrSgd58t6d0KM8dhJ95Et/T7nlnXcZvtlm5K216rtvRNBmqV3BTK1OY=
    file:
      - builds/nonce-tools-app-darwin-x64.tar.gz
      - builds/nonce-tools-app-linux-x64.tar.gz
      - builds/nonce-tools-app-win32-ia32.tar.gz
    skip_cleanup: true
    overwrite: true
    prerelease: true
    on:
      branch: develop
      repo: nonce-community/nonce-work-tools
      tags: true

